### ISSUE TITLE
VCfloat extensions and automation

### ISSUE THREAD

**Issue by sampollard** [VeriNum/vcfloat#18]
This is a follow-up with our meeting with @anthonydario so I'm dictating here.

Because of software licensing issues we will have to be careful in separating VCfloat improvements with our application, but the following are some directions that would be useful to improve automation:

1. Add support for loops. I think for our use case, unrolling loops is fine since we can start with statically-known loop bounds.
2. Supporting input as an array of floats, if this is not already supported (i.e. `double foo(double *x, int n)`), assuming that the pointer is valid from `x[0..n-1]`.
3. Automatically proving absence of overflow. This is in general not possible, but we can simplify by assuming some reasonable input bound then.
4. Adding conditionals. This is low priority in my opinion, if only because the above are higher priority.

**Comment by andrew-appel** [comment]
Items 1 and 2 are something the user would do in the functional model, not really within VCFloat itself.  Item 3 is mostly taken care of by VCFloat itself, already.  As you say, "assume some reasonable input bound", but VCFloat already requires you to state the input bounds (though you're allowed to state vacuous ones).

I'd be happy to discuss and explain this sometime (after August 22nd).

**Comment by sampollard** [comment]
Thanks for getting back to me - I think I made this issue a bit prematurely without knowing the details of VCfloat. My original plan was to extend VCfloat by improving automation, but your answers indicate to me these are actually questions about generating the functional model.

The general goal I have is to make it "easy" to specify and prove small math utilities - which as far as I understand, LAProof has already done for the linear algebra building blocks. Our situation at Sandia is such that we want to be able to verify our own linear algebra (and other math) functions. The goal is a push-button verification, which is probably not feasible, but I want a spec (even if the error bounds are really loose) that I can quickly generate and prove, send to the developers, and then tweak as necessary.

Your comment indicates this goal is best accomplished by building tooling on top of VCfloat with potentially some special-purpose tactics.

I think a discussion would be valuable, let me send out an invitation to discuss some of these plans, expect an invite for some time early September.
